name = "techfeed-daily"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "KV"
id = "e80a7fda966d45caa629f0df14ba39f3"

[[d1_databases]]
binding = "DB"
database_name = "techfeed-daily-db"
database_id = "252d3a54-282d-419f-a105-b9d8e16f9ed5"

[build]
command = ""
